[build]
  command = "pnpm run build"
  publish = ".next"
  edge_functions = "true"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "pnpm run dev"
  port = 3000
  publish = ".next"
