[build]
  command = "pnpm run build"
  publish = ".next"
  edge_functions = "true"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm run dev"
  port = 3000
  publish = ".next"
